### ISSUE TITLE
Zappa 0.3.1 doesn't work with node 0.6.0

### ISSUE THREAD

**Issue by chees** [mauricemach/zappa#108]
Zappa depends on express 2.4.x which depends on node (>= 0.4.1 < 0.5.0).
express 2.5.0 is available for node 0.6.0, so perhaps zappa's dependency can be updated?

**Comment by victusfate** [comment]
It always takes a couple of days to shake out dependency updates, no doubt Zappa will be 0.6.0 ready in no time.
I haven't read through node 0.6.0 updates yet, any significant changes?

**Comment by JasonMiesionczek** [comment]
Figures the day I learn about zappa, I can't use it :(

**Comment by michaelsbradleyjr** [comment]
Quick work around:

_(tested with node v0.6.1)_

```
$ mkdir myproj
$ cd myproj/
$ npm install zappa --force
```

With the `--force` flag, express@2.4.7 is installed (check with `npm ls` in the myproj directory), despite the engine version mismatch indicated in its package.json. I created a test server.coffee, fired it up, and it seems to work.  Obviously, a better solution is for zappa to be updated/upgraded and tested with respect to all its dependencies.

**Comment by smathy** [comment]
I've just been testing zappa with the latest version of all its dependencies, on node 0.6.1 and it seems to all be working well.  I'm stupid busy until Tuesday, but will submit a PR if @mauricemach hasn't updated this by then.

**Comment by mauricemach** [comment]
Published v0.3.3 (v0.3.2 had a publishing error) which works with express 2.5.x and node 0.6.x. Had to fix two minor issues for the tests to run (a38d2f1d9c43045e32c1379dd7640bc5a3c6e92a and 24e626c43752e3789bedf0beaeec100b1103c682). If you find anything else, feel free to reopen.
