### ISSUE TITLE
socket.io broadcast exceptions (blacklist)

### ISSUE THREAD

**Issue by Ond** [mauricemach/zappa#11]
It's unclear to me how one would pass an array of excepted session ID's to the broadcast method, when using the socket.io implementation. Is this possible in Zappa?

**Comment by mauricemach** [comment]
Not sure what you mean exactly. But at both request and message handlers, you have access to the same `app` object, which you can use to share data between them. See `/examples/websockets.coffee`.

**Comment by Ond** [comment]
See: https://github.com/LearnBoost/Socket.IO-node
Documentation > Listener > Methods > Broadcast

"Broadcasts a message to all clients. Optionally, you can pass a single session ID or array of session IDs to avoid broadcasting to, as the second argument."

**Comment by mauricemach** [comment]
Pushed to master. You can now do:

```
# except = id or array of ids
broadcast 'said', {id: id, text: @text}, except
```

Thanks for bringing this to my attention!

**Comment by Ond** [comment]
Great! Thanks.
