### ISSUE TITLE
node uuid 1.2.0 not found.. latest being 1.3.3

### ISSUE THREAD

**Issue by fastmover** [mauricemach/zappa#120]
I'm installing with npm, it fails finding dependency node-uuid 1.2.0  
I also am using NVM for node management, not sure if this may be causing an issue or not.

**Comment by barvian** [comment]
+1, just experienced the same issue, no NVM

**Comment by barvian** [comment]
Actually, just tried it a few days ago and the issue seems to be resolved.

**Comment by fastmover** [comment]
Confirmed, we are all good.  npm found node-uuid 1.2.0
