### ISSUE TITLE
/zappa/src/../vendor/jquery-1.6.4.min.js missing

### ISSUE THREAD

**Issue by fastmover** [mauricemach/zappa#121]
Maybe I'm not using this repository right, but every script i try to run in this framework error's on missing jquery inside some nonexistent vendor folder: /zappa/src/../vendor/jquery-1.6.4.min.js

**Comment by iangreenleaf** [comment]
Try running `cake vendor` and `cake build`. @mauricemach adds this stuff manually to the npm builds.

**Comment by fastmover** [comment]
You rock!
