### ISSUE TITLE
zappa fails with the long "watch" flag (--watch)

### ISSUE THREAD

**Issue by 525c1e21-bd67-4735-ac99-b4b0e5262290** [mauricemach/zappa#17]
Running...

```
zappa --watch FILE
```

...will cause zappa to hang indefinitely.

NFI why. I had a quick look but couldn't find a reason as to why this would occur. I doubt it's an issue in coffee-script/optparse but it's certainly possible.

I'll look into it later.

**Comment by mauricemach** [comment]
Thanks for catching it, it was a silly problem with the way I was forwarding the parameters to the spawned child. Fixed on master.

**Comment by 525c1e21-bd67-4735-ac99-b4b0e5262290** [comment]
Excellent. It's indeed fixed. Closing...
