### ISSUE TITLE
zappa shouldn't silently exit when running an "empty" file

### ISSUE THREAD

**Issue by 525c1e21-bd67-4735-ac99-b4b0e5262290** [mauricemach/zappa#18]
At the moment if you make an "empty" app with some contents in public...

```
cd ~
mkdir empty_zappa_app
cd empty_zappa_app
touch app.coffee
mkdir public
echo "bar" > public/foo
```

... and then run zappa...

```
zappa app.coffee
```

...it will silently exit.

Instead it should run and serve static assets from `public`

If you want people to realise that their app is empty then display a warning but I believe what I have proposed is the expected behavior.

**Comment by mauricemach** [comment]
Pushed it to master. Previously a zappa app would only be created if any handler definition (get, post, msg, etc) was called. Now apps.default is created and initialized regardless, even if app.coffee is completely empty. It will also serve static files from /public like any zappa app does by default.

**Comment by 525c1e21-bd67-4735-ac99-b4b0e5262290** [comment]
Excellent. Testing now...

**Comment by 525c1e21-bd67-4735-ac99-b4b0e5262290** [comment]
Confirmed fixed on master. Closing...
