### ISSUE TITLE
error running zappa

### ISSUE THREAD

**Issue by polidore** [mauricemach/zappa#21]
in cygwin, i get this error:

<pre>
$ zappa cuppa.coffee
Error: ENOENT, No such file or directory 'node'
    at Object.openSync (fs.js:167:18)
    at Object.readFileSync (fs.js:88:15)
    at Zappa.read (/usr/local/lib/node/.npm/zappa/0.1.3/package/lib/zappa.js:67:17)
    at Zappa.run_file (/usr/local/lib/node/.npm/zappa/0.1.3/package/lib/zappa.js:71:75)
    at Object.run_file (/usr/local/lib/node/.npm/zappa/0.1.3/package/lib/zappa.js:650:23)
    at Object.<anonymous> (/usr/local/lib/node/.npm/zappa/0.1.3/package/bin/zappa.coffee:96:15)
    at Object.<anonymous> (/usr/local/lib/node/.npm/zappa/0.1.3/package/bin/zappa.coffee:100:4)
    at Module._compile (node.js:329:23)
    at Object.run (/usr/local/lib/node/.npm/coffee-script/1.0.0/package/lib/coffee-script.js:55:19)
    at /usr/local/lib/node/.npm/coffee-script/1.0.0/package/lib/command.js:120:29
</pre>

Using node 0.3.1.  Here is my package situation:

<pre>
$ npm list installed
npm info it worked if it ends with ok
npm info using npm@0.2.13-3
npm info using node@v0.3.1
coffee-script@1.0.0    Unfancy JavaScript    =jashkenas active installed latest remote stable javascript language coffe
coffeekup@0.2.1        Markup as CoffeeScript.    =mauricemach active installed latest remote template view coffeescrip
connect@0.5.2          High performance middleware framework    =creationix =tjholowaychuk active installed latest remo
express@1.0.0          Sinatra inspired web development framework    =tjholowaychuk active installed remote framework s
express@1.0.1          Sinatra inspired web development framework    =tjholowaychuk installed latest remote framework s
htmlparser@1.7.3       Forgiving HTML/XML/RSS Parser in JS for *both* Node and Browsers    =tautologistics active insta
jquery@1.4.3           jQuery: The Write Less, Do More, JavaScript Library    =coolaj86 active installed latest remote
jsdom@0.1.20           CommonJS implementation of the DOM intended to be platform independent and as minimal/light as p
mjsunit.runner@0.1.3   Command line mjsunit runner which provides an easy way to hook into mjsunit and start running te
npm@0.2.13-3           A package manager for node    =isaacs active installed latest remote package manager modules ins
request@0.10.0         Simplified HTTP request method.    =mikeal active installed latest remote
socket.io@0.6.3        The cross-browser WebSocket    =rauchg =Tim-Smart active installed latest remote
zappa@0.1.3            Razor-sharp DSL for modern web apps.    =mauricemach active installed latest remote framework we
npm ok

</pre>

coffee and node work independently

<pre>
$ cat test.coffee
console.log 'Test'

$ coffee test.coffee
Test

</pre>

Help!

**Comment by dwillis** [comment]
I've had this error, too, using CoffeeScript 1.0. Rolling back to CS 0.9.X works fine.

**Comment by jaekwon** [comment]
https://gist.github.com/756581

**Comment by mauricemach** [comment]
Released 0.1.4 which is compatible with coffeescript 1.0, can you confirm if it works in cygwin?

**Comment by polidore** [comment]
works now. thanks!

$ zappa

Usage:
  zappa [OPTIONS] path/to/app.coffee

Available options:
  -h, --help         Displays this wonderful, elucidative help message
  -v, --version      Shows zappa version
  -p, --port         The port(s) the app(s) will listen on. Ex.: 8080 or 4567,80,3000
  -n, --hostname     If omitted, will accept connections to any ipv4 address (INADDR_ANY)
  -c, --compile      Compiles the app(s) to a .js file instead of running them.
  -w, --watch        Keeps watching the file and restarts the app when it changes.
