### ISSUE TITLE
there's any way that use the Express's use/configure/set/register methods etc.

### ISSUE THREAD

**Issue by arden** [mauricemach/zappa#29]
there's any way that use the Express's use/configure/set/register methods etc.

i'm hope configure the Express use the Express' use/set/register methods in zappa?

**Comment by mauricemach** [comment]
Implemented in 0.2.0beta. You have direct access to the express server as `app` at the root and handler scopes, and also to the shortcuts `use`, `configure`, `set`, `enable` and `disable` at the root.
