### ISSUE TITLE
"coffee" not found.

### ISSUE THREAD

**Issue by leknarf** [mauricemach/zappa#35]
I receive an error: ''' "coffee" not found. ''' whenever I try to run the zappa command with any arguments (or no arguments).

```
$ zappa
"coffee" not found.
```

Coffee-script is installed and is executing the zappa.coffee file. This error is actually being thrown from within the script itself. Specifically, it's on line 92 of zappa.coffee in the following snippet:

```
if args.length is 0
    puts parser.help() if options.help or argv.length is 0
    puts zappa.version if options.version
    process.exit()
else
    file = args[0]

path.exists file, (exists) ->
    if not exists
        puts "\"#{file}\" not found."
        process.exit -1
```

I originally encountered the problems with npm described in issue #27, so it's possible this is a continuation of my configuration woes. But I believe I have npm set up correctly now:

```
$ npm -v
1.0.3
$ npm list
<my local path>
├── coffee-script@1.1.0 
└─┬ zappa@0.1.4 
  ├── coffee-script@1.1.0 
  ├── coffeekup@0.2.2 
  ├─┬ express@2.3.3 
  │ ├── connect@1.4.0 
  │ ├── mime@1.2.1 
  │ └── qs@0.1.0 
  ├─┬ jquery@1.5.1 
  │ ├── htmlparser@1.7.3 
  │ └─┬ jsdom@0.1.20 
  │   ├── mjsunit.runner@0.1.3 
  │   └── request@1.9.5 
  └── socket.io@0.6.17
```

I apologize if I'm overlooking anything obvious, but I'm a coffee-script/node beginner and I don't quite follow what that path.exists function call is intended to do.

**Comment by qur2** [comment]
I'm encountering the same problem (I'm also new to node & coffee-script). I also tried to clone from git and to sudo npm link (read in issue #27) but this won't change anything.
Hope to get some hints. Thanks.

**Comment by obowah** [comment]
coffe-script 1.1.0 says "When running via coffee executable, process.argv and friends now report coffee instead of node." - so someone could fix zappa.coffee for this change.

**Comment by leknarf** [comment]
That's great obowah, it's then an easy change. Line 17 of zappa.coffee should be 

```
if process.argv[0] in ['node', 'coffee'] and process.argv.length >= 2
```

Thanks again, this works for me now.

**Comment by qur2** [comment]
It now works for me too, thanks a lot.
