### ISSUE TITLE
autoreloading

### ISSUE THREAD

**Issue by ghost** [mauricemach/zappa#4]
Can Zappa do any kind of files autoreloading by default?

Autorestarters i've found are adapted for js files or analize files tree only once at start.

It would be nice if after every watched file change Zappa could reanalize "include"d dependencies or do it after each page refresh.

**Comment by mauricemach** [comment]
That's actually my biggest priority at the moment! I'm using zappa heavily and it's a royal pain to restart the server to see changes. I just haven't had the time to implement it yet but as soon as I do I'll post here.

**Comment by mauricemach** [comment]
Pushed initial support for auto-reloading to master, includes included. :) It may still need a lot of work, but seemed to get the job done here. Please tell me what you think.

**Comment by ghost** [comment]
Nice. Works for me.
