### ISSUE TITLE
Static compile option doesn't honor port setting

### ISSUE THREAD

**Issue by badslug** [mauricemach/zappa#43]
It does not seem possible to set an alternative server port while doing a static compile. The expected outcome of the following command:

```
zappa -c -p 8080 app.coffee
```

Expected: Should be a static version of the app that runs on port 8080:

$ node app.js
App "default" listening on *:8080...

Actual:

$ node app.js
App "default" listening on *:5678...

**Comment by dimroc** [comment]
Seems like this functionality would be required to host a zappa application on a PaaS such as Heroku.

**Comment by dimroc** [comment]
Maybe the following link will show you how to configure the app to run on a particular port:

https://github.com/mwl/cloudzappa

**Comment by mauricemach** [comment]
@mwl's example is really the best solution for 0.1.x.

Thanks to your input, 0.2.x was designed to make this a non-issue:

```
require('zappa') port, hostname, ->
  get '/': 'hi'
```
