### ISSUE TITLE
Compatibility with Joyent No.de service & VMWare CloudFoundry

### ISSUE THREAD

**Issue by badslug** [mauricemach/zappa#44]
Joyent's No.de and VMWare's CloudFoundry node hosting services pull server settings from environmental variables. An example app written to work on a local developer box as well as the No.de service would be:

```
var http = require('http');

var server = http.createServer(function (req, res) {
  res.writeHead(200, { "Content-Type": "text/plain" })
  res.end("Hello world\n");
});

server.listen(process.env.PORT || 8001);
```

They both also assume that the main node entry point is a file named server.js (although other services may change this setting). To be more compatible with these services, it would be very helpful to:
1. Allow any command line setting to also be configured via source code at runtime. This will accommodate these service's particular setups without forcing special command line build settings for deployment.
2. Allow the compile flag to specify an output file name as well as the input file name.
3. Allow via code, a way to specify require.paths.unshift settings to point to the correct server npm directories for these services (some of which are defined at runtime via environmental variables by these hosting environments). Currently with require('zappa') as the first line of the compiled app.js file, there is no way to bootstrap zappa usage without manually editing the compiled file to add the require.paths.unshift.

I think these services will be a popular way to deploy node services and supporting them will help with zappa adoption. Thanks.

**Comment by mauricemach** [comment]
Thanks a lot for your feedback Iain, and sorry for the late reply!

The zappa command was conceived when the node ecosystem was much younger and was intended to make my life easier, handling auto-reloading and maybe even deployment in the future. But as this ecosystem evolved and tons of solutions became available, the command (and the dependency on it) became not only superfluous but even a hindrance. 

Inspired by this post and my own experiences deploying zappa, in 0.2.x I'm dropping the command, and providing a minimal API instead to run zappa code:

```
require('zappa') ->
  get '/': 'hi'
```

To specify port and host:

```
require('zappa') 1234, 'domain.com', ->
  get '/': 'hi'    
```

If you think I'm still missing anything, please let me know!

**Comment by badslug** [comment]
Hi

No problem on the delay, I know how busy things can be. I think you solution looks good. The only possible missing piece I can think of is to continue to have the option to auto-reload the app during development. It is an insanely useful feature and I'm not sure how well the separate standalone reloaded libraries will handle the coffee script files (if they do work though, keeping Zappa simple makes sense). Thanks for the great tool

-iain

**Comment by mauricemach** [comment]
Forgot to mention it!

I've been using `run` and it works like a charm with .coffee directly:

```
npm install run -g
runjs app.coffee
```

**Comment by badslug** [comment]
Awesome - sounds perfect. Thanks

-iain
