### ISSUE TITLE
'in' operator broken when used in client script

### ISSUE THREAD

**Issue by mrjf** [mauricemach/zappa#50]
To facilitate the `in` operator to check for list membership, CoffeeScript generates `var __indexOf` and puts this at the top of the JS output.  When you use `in` in a `client` script in Zappa, the `__indexOf` bit doesn't get put into the client-side JS script, so `in` causes an error:

``` coffeescript

get '/': ->
  render 'index'

client 'test': ->
  foo = ['a', 'b']
  if 'a' in foo
    console.log 'Yes'

view index: ->
  script src: '/test.js'
  iframe src: '/test.js'
```

The script `test.js` is written with `__indexOf` undefined:

``` javascript
;(function () {
      var foo;
      foo = ['a', 'b'];
      if (__indexOf.call(foo, 'a') >= 0) {
        return console.log('Yes');
      }
    })();
```

Loading this page yields `Uncaught ReferenceError: __indexOf is not defined`.

Thanks a million for Zappa!

**Comment by mrjf** [comment]
To clarify -- this bug is on the 0.1.5 release. Congrats on the 0.2 release, new features look awesome.

**Comment by mauricemach** [comment]
0.1.x is kind of a lost cause, but this change is very straightforward. Pushed to the [0.1.x branch](https://github.com/mauricemach/zappa/tree/0.1.x). Thanks!

**Comment by mrjf** [comment]
Thanks! Looking forward to moving to 0.2 and all the new goodies.

**Comment by mauricemach** [comment]
Make sure you don't miss the migration guide: https://github.com/mauricemach/zappa/blob/master/docs/migration.md

Your feedback is very welcome too!
