### ISSUE TITLE
Error: Cannot find module 'zappa' (zappa 0.2.0beta, npm 1.0.1rc5, node v0.5.0-pre)

### ISSUE THREAD

**Issue by mrjf** [mauricemach/zappa#53]
I know this issue has been covered before (https://github.com/mauricemach/zappa/issues/27, https://github.com/mauricemach/zappa/issues/34) but I just wanted to point out it is again a factor with new versions of npm, node, and zappa.

Running the commands in the documentation:

`npm install node`
`coffee cuppa.coffee`

I get: `Error: Cannot find module 'zappa'`

If I alter `cuppa.coffee` to read `require('./node_modules/zappa') ->`, things work.

I did try setting my `$NODE_PATH` environment variable as some of the earlier fixes suggested, but that did not help.

Sorry if I missed the solution in the other tickets, or am just not thinking clearly. Thanks for Zappa!

(OS X 10.6.8)

**Comment by mauricemach** [comment]
Thanks for reporting!

I'm on 10.6.8 too, npm 1.0.22, node 0.4.10 (installed by nvm) and I don't get this error. I'll try 0.5.0 to see how it goes.

**Comment by mauricemach** [comment]
v0.5.0 from nvm works fine too.

I installed node 0.5.0 from scratch according to the [official instructions](https://github.com/joyent/node/wiki/Installation) but couldn't install zappa since express requires node < 0.5.0 (did you get this too?). Then I did the same with 0.4.10, and zappa installed and ran fine.

How did you install your node and npm? What's your CoffeeScript version?

**Comment by mrjf** [comment]
CoffeeScript version 1.1.0-pre

It's been a while, but I believe I installed node.js by downloading and building from source in the usual way (http://nodejs.org/#download).  Libraries are in `/usr/local/lib/node` and binary is in `/usr/local/bin/node`.

I installed npm via the one-liner at http://npmjs.org/. Binary is `/usr/local/bin/npm`, libraries are in `/usr/local/lib/node_modules/npm/` (I think?).

Let me know if there's anything I can do to fill in more info or test anything. Thanks!

**Comment by mrjf** [comment]
No, I didn't get any warning about installing Zappa on Node v0.5.0-pre. And it works, too. Odd. Maybe I have another older Node floating around that is not on my path, but npm knows where it is and uses it? Can't find one, though.

**Comment by mauricemach** [comment]
If you npm install, say, express at the same folder, can you require it from `cuppa.cofffee`?

Also, if you add a `zappa/lib/index.js` containing `module.exports = require("./zappa")`, does it make any difference?

**Comment by mrjf** [comment]
I cannot `require('express')` after installing locally and running `coffee cuppa.coffee`. I can, however, require zappa or express from the Node.js REPL.

Seems then that the problem is with my coffee. OK, I upgraded to coffee-script@1.1.2 and now all is well! Thanks for the help!

If anyone else has a similar problem, I would say to check whether you can require locally installed modules from within the node REPL, and if so, trying updating your CoffeeScript -- using npm, not using a source install.

**Comment by mrjf** [comment]
Oh, and adding the `index.js` file earlier did not help, nor is it necessary now with the new CoffeeScript. Clearly this was a bug in my environment and not to do with zappa. Excited to be moving forward with 0.2.

**Comment by mauricemach** [comment]
Nice!
