### ISSUE TITLE
Ajax post request parameters are not visible in the handler

### ISSUE THREAD

**Issue by ilyabo** [mauricemach/zappa#54]
In the following example the value of @finding which is printed in the console is undefined:

```
require('zappa') ->

  get '/': ->
    render 'home'

  view home: ->
    table ->
      td -> label 'Finding: '
      td -> input type:'text',id:'finding_text'
      td -> input type:'button',id:'submit_finding',value:'Submit'
      script src: '/study.js'


  coffee '/study.js': ->
    $('#submit_finding')
      .click ->
        finding = $('#finding_text').val()
        unless finding is ''
          $.ajax
            type: 'post'
            url: '/submit_finding'
            dataType: "json"
            data: 
              finding: finding

            success: ->
              $('#finding_text').val('')



  post '/submit_finding': ->
    console.log @finding

    send 
      result: 'Ok'


  view layout: ->
    html ->
      head ->
        script src: 'http://code.jquery.com/jquery-1.6.2.min.js'
      body ->
          @body
```

As soon as I change 'post' to 'get' in the ajax request type and the handler, the value of @finding is properly set.

I checked the ajax request details in the Chrome console: the finding parameter is properly sent, so it is probably not jQuery's fault.

What could be the reason for this?

**Comment by mauricemach** [comment]
You have to use the bodyParser middleware:

```
use 'bodyParser'
```

**Comment by ilyabo** [comment]
This works magically :) Thanks again!

**Comment by ilyabo** [comment]
By the way, is there a standard way of doing ajax in zappa (or express) or is using jquery for that just fine?

**Comment by mauricemach** [comment]
No preferred way, you can use whatever you like. I use jQuery too.
