### ISSUE TITLE
Minor typo in readme.md: shared '/index.js', -> should be shared '/index.js': ->

### ISSUE THREAD

**Issue by mrjf** [mauricemach/zappa#55]
`shared '/index.js', ->`

should be

`shared '/index.js': ->`

Comma should be colon, that's all.

**Comment by mauricemach** [comment]
A small character that can cause a lot of confusion! Thanks for reporting. Fixed that in '/docs/reference.md' too.

**Comment by mrjf** [comment]
Thanks!
