### ISSUE TITLE
client_routes.coffee demo broken (in fact sammy)

### ISSUE THREAD

**Issue by cognominal** [mauricemach/zappa#62]
Installing zappa with 'npm install -g zappa', I try to run client_routes.coffee.

In the debug output, I see ReferenceError: ren is not defined
In web inspector I see that sammy.js was not loaded.

Also, I had to use safari because websockets get disconnected with chrome.

running 

>  ack --nocolor --nogroup  -w -- ren

on the zappa hierarchy I got

>  ...
>  lib/zappa.js:406:        return ren.send(sammy);
>  src/zappa.coffee:283:      ren.send sammy
>  ...

Sounds like a typo to me, "ren" should read "res".

**Comment by mauricemach** [comment]
Fixed in 08c55f34. Sorry about that.
