### ISSUE TITLE
Problems adding middleware

### ISSUE THREAD

**Issue by pikeas** [mauricemach/zappa#63]
`use cookieParser` (per Zappa's docs) does not work. The same is true for logger and session.

`use express.cookieParser` also fails. Only the form `use express.cookieParser()` works.

**Comment by mauricemach** [comment]
The first example is missing the single quotes: it should be `use 'cookieParser'`.

Example #2 (`use express.cookieParser`) also isn't supposed to work. Express/connect middleware are supposed to be called to return the correct function.

**Comment by pikeas** [comment]
Abandoned project, closing issue.
