### ISSUE TITLE
ability to configure socket.io transport options

### ISSUE THREAD

**Issue by dimroc** [mauricemach/zappa#65]
Hi,
I'm trying to configure the socket.io transport order precedence as defined in the socket.io documentation here:

http://labs.learnboost.com/socket.io/

But I am at a loss as to when and how in the zappa framework one can configure the socket.io options. The ctor for the socket.io (new io.Socket(...)) gets called inside zappa and I'm not familiar with how to configure socket.io after the fact.

The main reason for this is that the current socket.io release breaks on the latest version of chrome (they changed their websocket implementation) and I must override socket.io to do xhr-polling rather than websockets.

Thanks.

**Comment by mauricemach** [comment]
At the root scope you have access to `io`. With [io.set](https://github.com/LearnBoost/Socket.IO/wiki/Configuring-Socket.IO) you can configure transports:

```
require('zappa') ->
  io.set 'transports', ['xhr-polling', 'websocket', 'flashsocket', 'htmlfile']
```

**Comment by dimroc** [comment]
Thanks
