### ISSUE TITLE
socket.io client-side events aren't called correctly.

### ISSUE THREAD

**Issue by dimroc** [mauricemach/zappa#67]
Hi,
I'm in the process of slimming down a sample that better illustrates the bug, but the issue seems to be the fact that regardless of whatever you emit (ie: emit 'first_event'), the last client-side event handle gets called, instead of the one with the appropriate label.

``` coffee-script
# NOTICE: The wrong event handler gets invoked when running this code!
  at connection: ->
    console.log "CONNECTION"
    emit 'test_hook'

  client '/collab.js': ->
    connect()

    at 'test_hook': ->
      console.log "HOOK"

    at 'bullshit': ->
      console.log "bullshit"
```

The full source, if you want to run it, is here.
https://github.com/dimroc/collabcode

The file in question is collabs.coffee.

**Comment by mauricemach** [comment]
Sorry about that, fixed in master (#58).

**Comment by dimroc** [comment]
Any chance a new npm release of zappa 0.2 will be out soon  to address this issue? Or should I run zappa from source?

**Comment by mauricemach** [comment]
I'll release 0.2.0 soon (hopefully this week). I'll announce it at the new [mailing list](https://groups.google.com/group/zappajs) when it's out.
