### ISSUE TITLE
npm link-ing zappa

### ISSUE THREAD

**Issue by rdrey** [mauricemach/zappa#69]
I'm feeling a little stupid, and I don't think this is really zappa's problem but here it goes:

`npm install zappa` is no problem, but I'd like to use `npm link` to a git repo to always use the latest and greatest zappa. 

So I `git clone zappa`, `cd` into the repo, do a `sudo npm link` and get the following:

```
/usr/local/lib/node_modules/zappa -> /Users/rainerdreyer/Workspace/zappa
```

Now in my project: `npm install` ... it pulls zappa from the interwebs. Then I do a `npm link zappa`.
The output:

```
./node_modules/zappa -> /usr/local/lib/node_modules/zappa -> /Users/rainerdreyer/Workspace/zappa
```

unfortunately require('zappa') fails. Any pointers?

**Comment by mauricemach** [comment]
You're missing `cake build`, right after `cd`ing into the cloned repo.

BTW, after that the only command you need in your project dir is `npm link zappa`.

**Comment by rdrey** [comment]
Perfect, thanks again!
