### ISSUE TITLE
npm nstalled 0.2.0beta, got no binary

### ISSUE THREAD

**Issue by abrookins** [mauricemach/zappa#72]
E.g.:

$ npm -v
1.0.13

$ npm install zappa@0.2.0beta
zappa@0.2.0beta ./node_modules/zappa 
├── coffeekup@0.3.0beta (coffee-script@1.1.2)
├── express@2.4.3 (mime@1.2.2 qs@0.3.1 connect@1.7.0)
├── socket.io@0.7.7 (policyfile@0.0.3 redis@0.6.0 socket.io-client@0.7.4)
└── jsdom@0.2.1

$ ls node_modules/.bin
(emptiness)

$ ls node_modules/zappa 
CHANGELOG.md  Cakefile      LICENSE       README.md     benchmarks/   docs/         examples/     lib/          node_modules/ package.json  src/          vendor/

Whereas with 0.1.5 I get:

$ npm install zappa@0.1.5
zappa@0.1.5 ./node_modules/zappa 
├── coffee-script@1.1.2
├── coffeekup@0.3.0
├── express@2.4.6 (mime@1.2.2 qs@0.3.1 connect@1.7.0)
├── socket.io@0.8.4 (policyfile@0.0.4 redis@0.6.6 socket.io-client@0.8.4)
└── jquery@1.6.2

$ ls node_modules/.bin
zappa@

$ ls node_modules/zappa
CHANGELOG.md  Cakefile      LICENSE       README.md     bin/          examples/     lib/          node_modules/ package.json  src/          test/

$ ls node_modules/zappa/bin
zappa*

**Comment by abrookins** [comment]
Ugh, I need to read the docs before I submit an issue.

**Comment by mauricemach** [comment]
For anyone revisiting this issue, the relevant docs are [here](http://zappajs.org/docs/peaches). The binary was removed in 0.2.x because it's not necessary anymore.
