### ISSUE TITLE
Attaching event handlers directly

### ISSUE THREAD

**Issue by smathy** [mauricemach/zappa#78]
It'd be great to be able to do this:

```
button "foo", "Foo", onclick: ->
  get "/foo"
```

Instead of having to attach it in the onload.

**Comment by mauricemach** [comment]
Oops, I just realized this issue was created in zappa instead of coffeekup! Can you recreate it there? Thanks!

**Comment by smathy** [comment]
Oops, done: https://github.com/mauricemach/coffeekup/issues/79
