### ISSUE TITLE
Doesn't find jqyery.min when installed using npm

### ISSUE THREAD

**Issue by neapel** [mauricemach/zappa#82]
For some reason my nodejs packages are installed into ~/usr/lib/nodejs.
Trying to run a minimal `require('zappa')` server fails with:

<pre>
Error: EBADF, Bad file descriptor '~/usr/lib/nodejs/.npm/zappa/0.2.0/package/
  lib/../node_modules/jquery/dist/node-jquery.min.js'
</pre>

Because `.npm/zappa/0.2.0/package/node_modules` doesn't exist. The only jQuery file in question is actually in `.npm/jquery/1.6.2/package/dist/node-jquery.min.js`

`sammy-latest.js` is being loaded the same way but actually exists at that location.

This can be solved using

<pre>
cd ~/usr/lib/nodejs/
cd .npm/zappa/active/package
mkdir node_modules
ln -s ../../../../jquery/active/package node_modules/jquery
</pre>

(but I guess there's a less fragile way?)

**Comment by mauricemach** [comment]
Since b718272 I'm not getting jquery from the npm package anymore, it's vendored just like sammy. So this issue won't be present when 0.2.1 is released.

Anyway, I'm curious as to why you don't have a `node_modules` dir under zappa. Are you on npm 1.x?

**Comment by neapel** [comment]
I was using npm 0.2.19 (from ubuntu), didn't realize it was _that_ old. Using npm 1.0.30 it works.

**Comment by mauricemach** [comment]
I must add a "make sure you're on npm 1.x" note to the installation instructions, it changed completely from 0.x and a lot of people didn't notice. I think I wouldn't myself, if I wasn't involved in module development.

**Comment by neapel** [comment]
Too bad depending on `"npm": ">= 1.0.0"` generates an awkward warning (and installs npm again…)

**Comment by mauricemach** [comment]
Never thought of doing that, it's meta as hell! :)
