### ISSUE TITLE
Can't npm install zappa

### ISSUE THREAD

**Issue by sarenji** [mauricemach/zappa#98]
I've been running into problems installing zappa. I get `npm install` errors because libs require different versions of node. When using node v0.4.11 stable:

```
$ nvm use v0.4.11
$ npm install zappa
npm ERR! Not compatible with your version of node/npm: connect@2.0.0alpha1
npm ERR! Required: {"node":">= 0.5.0 < 0.7.0"}
npm ERR! Actual:   {"npm":"1.0.27","node":"v0.4.11"}
```

And with v0.5.8:

```
$ nvm use v0.5.8
$ npm install zappa
npm ERR! Not compatible with your version of node/npm: express@2.4.6
npm ERR! Required: {"node":">= 0.4.1 < 0.5.0"}
npm ERR! Actual:   {"npm":"1.0.27","node":"v0.5.8"}
```

I'd really like to use zappa on a production server but I'm a bit stuck at this step since putting zappa in package.json and pushing to the server would still run into the above problems. Any idea on where to go from here?

**Comment by mauricemach** [comment]
Hmmm, it seems this was [just recently fixed](https://github.com/visionmedia/express/commit/77f885d4a0f043667a812d79d93e0e99ef555cb4) in express 2.4.7. I'll push a zappa 0.3.1 with the updated express dep.

**Comment by mauricemach** [comment]
Feel free to reopen if the problem persists.

**Comment by sarenji** [comment]
Wow, thanks for the _super_ fast response. The issues I had are all fixed
now!
